### ISSUE TITLE
Issues unpacking lo.tar.br

### ISSUE THREAD

**Issue by jonogan** [vladgolubev/aws-lambda-libreoffice#1]
Hi @vladgolubev,

I have been trying to use this package instead, but continue to have trouble. I saw that abdulbarik was able to get it working so I assume the issue is on my end. The function seems to hang on the getExecutablePath() function, and specifically the last line where it's piping the decompressStream. I've pasted my lambda function below, do you mind seeing if it's something in my implementation?

`const {writeFileSync, readFileSync} = require('fs');
const {execSync} = require('child_process');
const {parse} = require('path');
const {S3} = require('aws-sdk');
const fs = require('fs');

const s3 = new S3({params: {Bucket: 'convert-doc-to-pdf'}});

exports.handler = async ({filename}) => {
  console.log(filename);
  const {Body: inputFileBuffer} = await s3.getObject({Key: filename}).promise();
  writeFileSync(`/tmp/${filename}`, inputFileBuffer);

  fs.readdirSync('/tmp').forEach(file => {
      console.log(file);
    });

  const {getExecutablePath, defaultArgs} = require('aws-lambda-libreoffice');

  const loBinary = await getExecutablePath(); // /tmp/instdir/program/soffice

  execSync(`${loBinary} ${defaultArgs.join(' ')} --convert-to pdf /tmp/${filename} --outdir /tmp`)

  const outputFilename = `${parse(filename).name}.pdf`;
  const outputFileBuffer = readFileSync(`/tmp/${outputFilename}`);

  await s3
    .upload({
      Key: outputFilename, Body: outputFileBuffer,
      ACL: 'public-read', ContentType: 'application/pdf'
    })
    .promise();

  return `https://s3.amazonaws.com/convert-doc-to-pdf/${outputFilename}`;
};`

**Comment by vladgolubev** [comment]
Hi @jonogan!

Can you please paste the output of Lambda? Especially what this code prints?

```js
fs.readdirSync('/tmp').forEach(file => {
	console.log(file);
});
```

**Comment by jonogan** [comment]
@vladgolubev I think I figured it out. I had created the lambda in the console instead of the CLI, and hadn't allocated enough memory to the function. When I upped it to > 300mb the function runs great! I did have a follow up. Should I move the call to getExecutablePath() outside of the main lambda async? Just wondering about calling it everytime the lambda runs vs just on the initial coldstart. Any advice there?

Thanks for the terrific work! This module is great!

**Comment by vladgolubev** [comment]
@jonogan glad to hear that! You better keep `getExecutablePath()` inside the `handler`. It checks if an archive is unpacked and doesn't impact performance on subsequent invocations. In case `/tmp` folder was wiped out due to a cold start or by accident - it will unpack archive again and cache for future use.

**Comment by jonogan** [comment]
Awesome! Thanks for the help! Closing this issue
