### ISSUE TITLE
does not work with node6

### ISSUE THREAD

**Issue by interisti** [vladgolubev/aws-lambda-libreoffice#15]
works as expected with node8, but we have all the lambdas locked to node6.
it throws `Error: Module version mismatch. Expected 48, got 57.` error.

 is there a instructions to how to generate `/src/iltorb/build/bindings/iltorb.node` for node 6?

**Comment by vladgolubev** [comment]
You can grab old version of `iltorb` from the repo I forked - https://github.com/alixaxel/chrome-aws-lambda/commit/972ea78bdcc10eb0875305818df99604fc2335a8#diff-be1b196d9da17347884cbb68500e8151

This was the commit which changed the binary from node 6 to node 8
