### ISSUE TITLE
converting pdf to pdf

### ISSUE THREAD

**Issue by wobeng** [vladgolubev/aws-lambda-libreoffice#16]
Hi,

Thank you for libreoffice  lambda

I tried converting pdf to pdf

[wowza.pdf](https://github.com/vladgolubev/aws-lambda-libreoffice/files/2338353/wowza.pdf)

to 

[wowza-converted.pdf](https://github.com/vladgolubev/aws-lambda-libreoffice/files/2338355/wowza-converted.pdf)

do you have a solution for the edges that have been cut off

**Comment by vladgolubev** [comment]
@wobeng I guess this is a bug to report to the LibreOffice. There are no parameters to configure when you resave pdf. Same will appear in the desktop software
